emit:
  - "@typespec/openapi3"
options:
  "@typespec/openapi3":
    emitter-output-dir: "{cwd}/.skmtc"
    openapi-versions:
      - 3.0.0
    file-type: "json"
    output-file: "openapi.json"
linter:
  extends:
    - "@typespec/http/all"